// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOTZgjG38We75rqxBVLY1fVoiZXNA02wI',
    appId: '1:312686783403:web:64d5dbd41cf6497c5d00ee',
    messagingSenderId: '312686783403',
    projectId: 'doscrphere',
    authDomain: 'doscrphere.firebaseapp.com',
    storageBucket: 'doscrphere.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1B4eELmDYMBUs_fFmJ2Xvvu0ZEjmwQvQ',
    appId: '1:312686783403:android:682a476c795056375d00ee',
    messagingSenderId: '312686783403',
    projectId: 'doscrphere',
    storageBucket: 'doscrphere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-9enUm6nD1LW_Yu0mcnkKL_wL8nAnZX0',
    appId: '1:312686783403:ios:eaf211a2f9222dac5d00ee',
    messagingSenderId: '312686783403',
    projectId: 'doscrphere',
    storageBucket: 'doscrphere.firebasestorage.app',
    iosBundleId: 'com.example.docshpere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-9enUm6nD1LW_Yu0mcnkKL_wL8nAnZX0',
    appId: '1:312686783403:ios:eaf211a2f9222dac5d00ee',
    messagingSenderId: '312686783403',
    projectId: 'doscrphere',
    storageBucket: 'doscrphere.firebasestorage.app',
    iosBundleId: 'com.example.docshpere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOTZgjG38We75rqxBVLY1fVoiZXNA02wI',
    appId: '1:312686783403:web:09858eb92a081e615d00ee',
    messagingSenderId: '312686783403',
    projectId: 'doscrphere',
    authDomain: 'doscrphere.firebaseapp.com',
    storageBucket: 'doscrphere.firebasestorage.app',
  );
}
