# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define the project
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Function to get Flutter root
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Install Flutter iOS pods
flutter_ios_podfile_setup

# Define the target for the Runner app
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter iOS Pods installation
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add Google Sign-In dependency
  pod 'GoogleSignIn', '~> 7.1.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Target for tests
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Post-install hook for additional build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
